### ISSUE TITLE
Is this necessary?

### ISSUE THREAD

**Issue by osef123** [block-core/blockcore-extension#56]
Is it possible not to show that ? it adds nothing for average user but confusion

![image](https://user-images.githubusercontent.com/3747761/152038080-2608b33e-440e-430e-84a5-c5360604b475.png)

**Comment by sondreb** [comment]
For sure, what about "create account" on the right-side menu. Check that out and please give feedback on that. It's fairly advanced now, maybe some "advanced" expander or something to hide off the manual edit of derivation path?

**Comment by osef123** [comment]
Yes derivation path is shown with the "create account" and that's ok.

I just think you have to make it as simple as possible visually, think of the 80 year old grandmother who doesn't understand anything. The slightest superfluous character can cause her to bug out ahah.

**Comment by sondreb** [comment]
Simplified and added the symbol:

![image](https://user-images.githubusercontent.com/309938/152060461-49ae2284-690e-4d1e-a6d2-8ae2cf70bc1b.png)
