### ISSUE TITLE
transfer set ammounts

### ISSUE THREAD

**Issue by junenuj14** [block-core/blockcore-extension#58]
hi, 

can we have either a button so we can send the "max" amount of token? so for example max supply - fees?

or alterenatively, maybe a slider like you have on some exchanges? 0 - 25 - 50 - 75 - 100% of the available balance?

thanks

**Comment by junenuj14** [comment]
perhaps if the amount available was above the datafield where you fill in the amount, and maybe button shaped it would be more apparent? I did find it though eventually by myself

**Comment by sondreb** [comment]
The "button label" was moved right above the amount input field. This should make it a bit more visible for users. I'm closing this issue now, we can revisit the UI later if it should look more like a button or not.

Screenshot showing the moved label and the tooltip on hover:

![image](https://user-images.githubusercontent.com/309938/159385400-f37abf8f-d63a-4082-8d9f-f3752c8404d7.png)
