### ISSUE TITLE
Endless error messages

### ISSUE THREAD

**Issue by drmathias** [block-core/blockcore-extension#59]
I created an account for BTC (Segwit) which resulted in the following error: ```Error: Http failure response for https://btc.indexer.blockcore.net/api/stats/info: 0 Unknown Error```

There seems to be endless retries as it continues to display error messages every ~15 seconds and this won't stop even when an error message is dismissed or the wallet is locked.

![image](https://user-images.githubusercontent.com/39023939/152155651-1815ad85-eea4-4a04-b330-c6ee5ce501a2.png)

I'd expect that once the error message pops up, the action has already been retried and it will not continue to retry.

**Comment by adrianocorneia** [comment]
I have tried this as well and the error messages keep popping up even after deleting the BTC account (which wasn't easy as sometimes the account disappeared from the list).

**Comment by sondreb** [comment]
It is only STRAX that is currently supported and suppose to be working. CRS will come soon. BTC is future into the future.

Is Bitcoin enabled on the CoinVault instance or did you test Blockcore instance?

**Comment by drmathias** [comment]
This is with the Blockcore instance. The issue is that for HTTP errors it seems it will retry forever. The only way I managed to get the error message to stop popping up was uninstalling and reinstalling the extension.

**Comment by adrianocorneia** [comment]
(You can also do it in CoinVault by adding an account and altering the derivation path.)

**Comment by sondreb** [comment]
This is expected behavior, it is running queries to see if there is any changes to the unused addresses. It fails because BTC is currently not supported in the APIs. We'll have to figure out a good way to fail and display this to users. Maybe show an status color similar to how other wallets does it, and not show errors for querying balances, etc.

**Comment by drmathias** [comment]
@sondreb Looks like you fixed this, so closing

**Comment by sondreb** [comment]
There might still be some errors during initial startup, but it shouldn't continuously complain about errors.
