### ISSUE TITLE
typo in wallet

### ISSUE THREAD

**Issue by junenuj14** [block-core/blockcore-extension#60]
![image](https://user-images.githubusercontent.com/83215450/152165328-a156aaf9-ffbd-4627-8c1b-d26bbfbb91f1.png)
 
I believe the word "become" should be "becomes" 

incase the picture didn't load; it's in settings below the auto-lock timer datafield

**Comment by sondreb** [comment]
Thanks for the feedback, fixed and will be available in next update (0.0.8).

**Comment by junenuj14** [comment]
![image](https://user-images.githubusercontent.com/83215450/152169340-d720bc6d-3ee8-417c-9c48-1eb067acb9ce.png)

maybe nitpicking now, but I think "what" should be "which"? 

![image](https://user-images.githubusercontent.com/83215450/152169657-f2237f31-d0e0-47a9-b686-da6dc34119d8.png)

and over here I would replace "persisted" with "saved"
