### ISSUE TITLE
Implement a network status manager

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-extension#68]
Display the status of different networks that belongs to the accounts in the active wallet.

**Comment by drmathias** [comment]
It's nice to see the status indicator for the network against each account on the wallet overview. Potentially could do with a message when you navigate to an account, if it is not fully available. You may miss the indicator or it becomes unavailable when you're looking at this view.

![image](https://user-images.githubusercontent.com/39023939/153211314-9ce3d24a-3bf6-4ffb-87d5-e3cd210b6bab.png)

**Comment by sondreb** [comment]
Dashboard view:

![image](https://user-images.githubusercontent.com/309938/153717558-5c13bf38-1ae7-422e-9bcb-fe710ae959cb.png)

Account view:

![image](https://user-images.githubusercontent.com/309938/153717568-8439c9ac-3a6a-49d5-ae30-e0130ed5845c.png)

![image](https://user-images.githubusercontent.com/309938/153717587-0bbab317-0165-4e91-acda-11870e6757e9.png)

The status is not really "duplicated" in the screenshot, it's just that the status text is basic right now. Eventually it will have some more status details, and depends on error, etc.
