### ISSUE TITLE
Fee validation

### ISSUE THREAD

**Issue by drmathias** [block-core/blockcore-extension#80]
I was able to broadcast a [transaction](https://explorer.blockcore.net/tstrax/explorer/transaction/dc8b49683607da93f0940ba1ba5ed4b66248912cbe4587e665a0f74d7535a514) with a low fee (0.00000001 TSTRAX), which is stuck.

The wallet should validate the fee and prevent the user from doing this. Potentially, prevent the user from choosing a fee below a certain value. Alternatively, remove the option to set the exact fee entirely and instead give the user options, for example: low, medium and high.

**Comment by sondreb** [comment]
We are already querying this API endpoint to get network status:

https://strax.indexer.blockcore.net/api/stats

Here we have `relayFee+ which is the minimum that is required for the node to relay the transaction, afaik? Right @dangershony?

So we could code a minimum fee in the network definition in the extension, and then update that based upon what the actual indexer API returns?

The only blockchain where it makes sense to have option to choose between different fee levels, are Bitcoin and Ethereum. Unfortunately it's not deterministic to calculate the size of the transaction unless using schnorr signatures.

Thanks for the feedback and we will for sure add some improvements here.

**Comment by dangershony** [comment]
The plan is to get the feeKb from the api (also for different wait time) we could also return the min relay fee of each network.

**Comment by dangershony** [comment]
https://github.com/block-core/blockcore-indexer/issues/78

**Comment by sondreb** [comment]
Fee validation for all networks has been added. Closing this issue for now, but we must further improve the fee options for users, but at least it is no longer possible to send transactions that has lower than the fee that nodes will accept.
